import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {appColor} from '../../utils/colors/colors';
const STYLES = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: appColor.grey,
  },
  image: {
    width: wp('8%'),
    height: hp('4%'),
  },
  searchBar: {
    width: wp('90%'),
    height: hp('7%'),
    flexDirection: 'row',
    backgroundColor: appColor.grey,
    borderRadius: 10,
    alignItems: 'center',
  },
  headerContainer: {
    backgroundColor: appColor.white,
    height: hp('16%'),
    width: wp('100%'),
    alignItems: 'center',
  },
  contentContainer: {
    alignItems: 'center',
  },
  input: {
    paddingLeft: wp('2%'),
  },
  centered_View1: {
    flex: 1,
    backgroundColor: '#00000099',
  },
  Success_Modal: {
    width: wp('100%'),
    height: hp('70%'),
    marginTop: hp('30%'),
    backgroundColor: appColor.white,
    borderRadius: 30,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 3,
  },
  headingContainer: {
    alignItems: 'center',
    marginTop: hp('-1%'),
    marginBottom: hp('2%'),
  },
  textStyle: {
    color: appColor.black,
    fontSize: hp('2.3%'),
    fontWeight: 'bold',
  },
  textStyle1: {
    color: appColor.red,
    fontSize: hp('2%'),
    fontWeight: 'bold',
  },
  ItemContainer: {
    marginLeft: wp('5%'),
    marginTop: hp('2.5%'),
  },
  TextInput: {
    width: wp('85%'), 
    height: hp('7%'),
    backgroundColor: appColor.grey,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('1%'),
  },
  InputView: {
    width: wp('85%'), 
    height: hp('7%'),
    backgroundColor: appColor.grey,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('1%'),
    justifyContent: 'space-between',
    paddingHorizontal: wp('3%'),
  },
  TextInput1: {
    width: wp('85%'),
    height: hp('15%'),
    backgroundColor: appColor.grey,
    borderRadius: 10,
    flexDirection: 'row',
    marginTop: hp('1%'),
  },
  button: {
    width: wp('90%'),
    height: hp('7%'),
    position: 'absolute',
    marginLeft: wp('5%'),
    marginTop: hp('82%'),
    backgroundColor: appColor.red,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: hp('2%'),
    flexDirection: 'row',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 3,
  },
  button1: {
    width: wp('85%'),
    height: hp('7%'),
    marginLeft: wp('5%'),
    backgroundColor: appColor.red,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: hp('2%'),
    marginTop: hp('2%'),
    flexDirection: 'row',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 3,
  },
  textStyle2: {
    color: appColor.white,
    fontSize: hp('2%'),
  },
  button2: {
    width: wp('85%'),
    height: hp('7%'),
    marginLeft: wp('5%'),
    backgroundColor: appColor.white,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: hp('2%'),
    flexDirection: 'row',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 3,
  },
  textStyle3: {
    color: appColor.black,
    fontSize: hp('2%'),
  },
  textStyle4: {
    paddingLeft: wp('2%'),
  },
  taskContainer: {
    width: wp('75%'),
    height: hp('12%'),
    backgroundColor: appColor.white,
    borderRadius: 10,
    marginBottom: hp('2%'),
    marginLeft: wp('20%'),
    marginVertical: hp('1%'),
  },
  divider: {
    borderTopWidth: 1,
    borderTopColor: appColor.grey,
  },
  textStyle5: {
    color: appColor.red,
    fontSize: hp('2%'),
    marginLeft: wp('2%'),
  },
  textStyle6: {
    fontSize: hp('1.8%'),
    marginLeft: wp('2%'),
  },
  detailContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  optionsContainer: {
    position: 'absolute',
    marginTop: hp('90%'),
    width: wp('100%'),
    height: hp('7%'),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: appColor.white,
  },
  image1: {
    width: wp('6%'),
    height: hp('3%'),
  },
  optionButton: {
    height: hp('5%'),
    backgroundColor: appColor.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 3,
  },
  optionButtonText: {
    marginHorizontal: wp('3%'),
  },
  circle: {
    height: hp('3%'),
    width: wp('6%'),
    borderRadius: 100,
    borderColor: appColor.grey,
    borderWidth: 1,
    marginRight: wp('2%'),
    marginTop: hp('7%'),
    position: 'absolute',
    marginLeft:wp('66%')
  },
  circleView:{
    height: hp('3%'),
    width: wp('6%'),
    borderRadius: 100,
    borderColor: appColor.black,
    borderWidth: 1,
    position: 'absolute',
    marginRight: wp('2%'),
    marginTop: hp('7%'),
    marginLeft:wp('66%')
  },
  textStyle7:{
    marginRight:wp('2%'),
  }
});

export default STYLES;
